apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: suresha10/workflow-github-action:tagname
        ports:
        - containerPort: 8080
